name: 自动双源无损强行合并

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  fetch-and-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout own repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 1. 下载两个源
    - name: Fetch target files
      run: |
        mkdir -p datas
        curl -L "https://cnb.cool/fish2018/xs/-/git/raw/main/api.json" -o datas/cnb.json
        curl -L "https://raw.githubusercontent.com/FGBLH/GHK/refs/heads/main/海豚.json" -o datas/haitun.json

    # 2. 强行文本拼接合并
    - name: Text Merge JSON
      run: |
        python modify_config.py

    # 3. 提交
    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        git add .
        if [ -z "$(git status --porcelain)" ]; then
          echo "文件没有变化，无需更新。"
        else
          git commit -m "双源文本级硬核合并: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        fi
